### ISSUE TITLE
Doesn't change the *-Briding-Header.h name

### ISSUE THREAD

**Issue by samupp2758** [junedomingo/react-native-rename#101]
when the command is applied to the project, changes some stuff, less the Briding-Header,h file from ios folder, if Someone has the solution, please let me know.
ps: I love the package!

**Comment by EricWiener** [comment]
I had the same issue. I just manually changed the bridging header's name and updated the path of the bridging header in each of my target's info.plist. You can find the path under Build Settings -> Objective-C Bridging Header.

**Comment by samupp2758** [comment]
Thanks!

**Comment by vomchik** [comment]
Should be fixed in `2.5.0`

**Comment by pke** [comment]
I wonder, what is this header used for? I got the message, that its missing when I renamed my project. Is this essential?

**Comment by vomchik** [comment]
@pke No worries, this is not a required file. This file used for the case when you use objective-c modules in swift.
