### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by Spit-Biagio** [junedomingo/react-native-rename#102]
Hello, i try to change the application name & bundle
installation on emulator working, when i try to open the app, it crash... no error... just crash and still crash...
`"react-native": "0.62.2"`
any help? how i can fix it?

command runned is:
`react-native-rename "NewName" -b com.company.newname`

thanks!

**Comment by ShrikantRao** [comment]
Same issue here. I'm also on same version (0.62).

No App crash with no error on console. I tried `gradle clean`  and various other command but no luck.

I have set the app name containing 2 words (with a space) but when I check the app drawer the app shows just first word.

**Comment by Spit-Biagio** [comment]
yeah, no error app or console, i try with a name like Konan, no space or other, new bundle was... com.company.konan, before was com.company, maybe this is the problem?!? i hope that who made this package fix it, since i need it, i need to change my app name many time, because i build app that call api... 
maybe someone have other way to change app name and bundle ?

**Comment by mohit23x** [comment]
same issue, react native `0.62` app crashes on start

**Comment by hyorax** [comment]
same problem :/

**Comment by hyorax** [comment]
I solved it using this : [https://github.com/mayconmesquita/react-native-rename-next](url)

**Comment by bilalyaqoob** [comment]
there is the solution https://stackoverflow.com/questions/62805433/react-native-app-blinks-for-second-and-stops

**Comment by c7nasr** [comment]
this issue was for me. the problem that package removes MainActivity.java file. you have to restore it to the new directory and modify package name inside it too
and MainApplication too

\android\app\src\main\java\com

**Comment by AliAmjadHassan** [comment]
Install react-native-rename globally and then:
Steps to follow to change package and App Name Correctly:
1. Copy MainActivity.java and MainApplication.java from .\android\app\src\main\java\com\<YourAppName> and paste it somewhere else
2. Run command react-native-rename "NewName" -b com.company.newname
3.Paste MainActivity.java and MainApplication.java in .\android\app\src\main\java\com\<YourAppName>
4.Change the name of the package in MainActitvity.java and MainApplication.java manually 
5. go to ./android and run ./gradlew clean command from windows PowerShell
6. Delete any existing debug-app already installed on phone.
7. run command to start the app

**Comment by darron1217** [comment]
The path of `ReactNativeFlipper.java` is not changing on 2.6.0 latest.

**Comment by mshahzaib1629** [comment]
Thanks @AliAmjadHassan, it's working for me 👍

**Comment by vomchik** [comment]
Fixed in the last release v2.7.0
