### ISSUE TITLE
Should rename the InfoPlist.strings

### ISSUE THREAD

**Issue by anhtuank7c** [junedomingo/react-native-rename#105]
![Screen Shot 2020-06-26 at 09 34 26](https://user-images.githubusercontent.com/3163410/85814526-55bf5e80-b790-11ea-9bd2-d823b4cef119.png)

Should rename value of keys "CFBundleDisplayName" too.

See image bellow:

![image](https://user-images.githubusercontent.com/3163410/85814595-738cc380-b790-11ea-968d-3faf852abf04.png)

**Comment by GeekRishabh** [comment]
Hello @anhtuank7c You can have a look at my [PR ](https://github.com/junedomingo/react-native-rename/pull/104)for this

**Comment by junedomingo** [comment]
Closing, check v3 now.
