### ISSUE TITLE
Package/Bundle name

### ISSUE THREAD

**Issue by AliakseiRusetski** [junedomingo/react-native-rename#11]
Is it possible to create or rename package in android style: 
com.companyname.appname

**Comment by junedomingo** [comment]
Hi @AliakseiRusetski , this is not supported at the moment.

**Comment by junedomingo** [comment]
Hi @AliakseiRusetski ! i just updated the package, you're now able to add custom `BUNLDE_IDENTIFIER`, all you need to do is add `-b <yourBundleIdentifier>` option

eg. `react-native-rename "Travel App" -b com.junedomingo.travelapp `

Cheers! 😉

**Comment by 814k31** [comment]
@junedomingo Feature Request:
Allow changing the bundle identifier without requiring a new project name
So that I could use `react-native-rename -b <new bundle identifier>`

Useful if a user enters an invalid package name
