### ISSUE TITLE
ERROR: Can not open file after rename (react native ios)

### ISSUE THREAD

**Issue by xyz0405** [junedomingo/react-native-rename#115]
![Screen Shot 2020-11-01 at 12 06 37](https://user-images.githubusercontent.com/33455900/97795581-b24cf180-1c3a-11eb-9a20-257a658345b2.png)

`error: /Users/truongnguyen/Desktop/textSample/ios/Pods/Target Support Files/Pods-newName/Pods-newName.debug.xcconfig: unable to open file (in target "newName" in project "newName") (in target 'newName' from project 'newName')`

RN: 0.63.3

I just create a new project by react-native-cli and rename it. rename seem success but after rename, app build fail successfully. Please help.

**Comment by MinhNguyenWre** [comment]
Same issue. Any workaround?

**Comment by vomchik** [comment]
@xyz0405 @MinhNguyenWre Just made the same steps and all works fine.

Make sure that you run `pod install` after renaming.
![image](https://user-images.githubusercontent.com/732085/97804759-893c5900-1c5a-11eb-9bd9-1743b14273ad.png)
