### ISSUE TITLE
After renaming project ios build error

### ISSUE THREAD

**Issue by ranvirgorai** [junedomingo/react-native-rename#12]
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/ranvir/wslab/Myapp/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTRootContentView.o Base/RCTRootContentView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ranvir/wslab/Myapp/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTStatusBarManager.o Modules/RCTStatusBarManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

Installing build/Build/Products/Debug-iphonesimulator/Myapp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Myapp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by junedomingo** [comment]
Hey @ranvirgorai , What version of *react-native* are you using?

**Comment by danieljvdm** [comment]
Same issue

**Comment by junedomingo** [comment]
@danieljvdm What version of react-native are you using?

**Comment by danieljvdm** [comment]
I was on `0.43.4`

**Comment by danieljvdm** [comment]
I don't think the RN version matters here @junedomingo . My workspace was renamed but not the project.

**Comment by danieljvdm** [comment]
![image](https://user-images.githubusercontent.com/3450486/26965812-c940e452-4cf7-11e7-8859-7fa455dc82a8.png)

**Comment by junedomingo** [comment]
Have you tried cleaning it? (Product > Clean)

**Comment by danieljvdm** [comment]
I'll try, but I don't think that'll change the fact that the workspace has an incorrect reference to the project. sportapp was the old name and it didn't change the reference to the new one (NowNow).

**Comment by danieljvdm** [comment]
Found the problem - `contents.xcworkspacedata` isn't updating the project file reference to the new name.
