### ISSUE TITLE
Debug Application is not renaming

### ISSUE THREAD

**Issue by selvaTecky** [junedomingo/react-native-rename#122]
Hi,

I have renamed main application but I can't able to rename the debug application. can you help me on this?

**Comment by vomchik** [comment]
@selvaTecky Make sure that you use the latest version v2.7

**Comment by vishal9950** [comment]
@selvaTecky After you have run the script, clear the metro bundler cache with this command:
`npm start --reset-cache`. It should hopefully suffice the issue.

**Comment by selvaTecky** [comment]
Hi @vishal9950 ,

Even thought the debug folder files and packages are not getting updated.

**Comment by vishal9950** [comment]
@selvaTecky Try this,

For android:
1. `cd android`
2. `./gradlew clean`
3. `cd ..`
4.  `rm -rf node_modules && npm i && npm link (if using an older RN version)`
5. `npm run android`

For iOS:
1. `cd ios`
2. `rm -rf build`
3.  `cd ..`
4.  `rm -rf node_modules && npm i && npm link (if using an older RN version)`
5. `npm run android`

This should hopefully fix this problem 😶
