### ISSUE TITLE
Not working on iOS - RN 0.63.4

### ISSUE THREAD

**Issue by viper4595** [junedomingo/react-native-rename#124]
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-rename": "^2.7.0",

Hello,
When I run react-native-rename, the log in the terminal always shows success. But every file in /ios/ folder still keeps the old name. It works fine on Android.

**Comment by hamarles12** [comment]
Maybe your name value in your project's app.json file is not the same with the ios folders name. If yes, you can rename it first to match your ios folders name and rename again to new one.

**Comment by viper4595** [comment]
> Maybe your name value in your project's app.json file is not the same with the ios folders name. If yes, you can rename it first to match your ios folders name and rename again to new one.

It worked. Thank you very much!

**Comment by ericlifs** [comment]
Same issue is happening to me, not sure how to proceed based on your comment @hamarles12 .

**Comment by ericlifs** [comment]
The same issue was happening to me until I figured out the issue. You have to run the `react-native-rename "Name Of Your App"` while you at within the same app root folder.

**Comment by compelling** [comment]
Hi all. Have the same problem, used the rename tool previously with success but now it fails. Tried the tool on various RN 0.61 projects without success on for the iOS target.
I am running the command in the directory just above iOS and Android directory, and the script reports all modifications are done, but in fact nothing happens to the iOS directory. Android is fine. And yes, the name defined in app.json file is identical to the workspace name and project folders under iOS. 
Something has broken in this tool recently, tried to use previous versions but none of them work to a dependency of package "nomnom@1.8.1" that is no longer supported by Npmjs. 
Anyone else had these problems or have any ideas? Not sure if there are any error logs to look at or what else to try.

**Comment by vomchik** [comment]
@compelling Could you to use v2.8.0 and check if it works for you?

**Comment by vomchik** [comment]
@hamarles12  Thanks for the advice, I have added this checking to the library.

**Comment by compelling** [comment]
Seems to work fine now :)
