### ISSUE TITLE
Bug rename if NAME have space

### ISSUE THREAD

**Issue by truepatch** [junedomingo/react-native-rename#125]
RN 0.63.4

example
`npx react-native-rename "App Name" -b com.rn_starter.company`

![image](https://user-images.githubusercontent.com/3313882/106932936-27e4c400-673a-11eb-9c2f-fd204b74ab3d.png)
![image](https://user-images.githubusercontent.com/3313882/106932998-3c28c100-673a-11eb-83c7-a7e6c00e6fed.png)
![image](https://user-images.githubusercontent.com/3313882/106933065-4f3b9100-673a-11eb-9d96-1500e128eb54.png)

**Comment by truepatch** [comment]
My RegExp for fix this bug.

https://github.com/truepatch/simple-react-native-clone/blob/0458ae4d0473f2020fc1d98c58b429fa744c12d8/index.js#L235

**Comment by vomchik** [comment]
Thanks, fixed in v2.7.1
