### ISSUE TITLE
Renamed BUCK file cause unchanged bundle identifiers

### ISSUE THREAD

**Issue by momsse** [junedomingo/react-native-rename#127]
Hi,

Thanks for the great job done with that package 👌

It seems that `react-native@0.63.4` renamed `android/app/BUCK` to `android/app/_BUCK`. Bundle identifier still unchanged after `-b bundleIdentifier` run.

If the change is easy as adding the correct file in that line, I can help doing a PR for fixing that:

https://github.com/junedomingo/react-native-rename/blob/03ba1c733bfa01641f3c6762a37168f8c3ca99f8/src/config/bundleIdentifiers.js#L13

**Comment by vomchik** [comment]
Fixed in v2.7.1
