### ISSUE TITLE
[Bug] react-native-rename not working with expo inject project that generated from ignite cli

### ISSUE THREAD

**Issue by Ppang0405** [junedomingo/react-native-rename#129]
Log: 
Something went wrong:  TypeError: Cannot read property 'replace' of undefined
    at /Users/user/Desktop/MyApp/node_modules/react-native-rename/lib/index.js:98:42

The current app name in app.json of the expo injected app is different from the project generated from react-native-cli.
Please fix it.

**Comment by dimovdaniel** [comment]
Just add root "name" element in app.json

ex
```
{
  "name": "TravelApp", <-----
  "expo": {
    "name": "TravelApp",
    ...
    }
}
```

Hope it helps

**Comment by Ppang0405** [comment]
Tks
