### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by ramsestom** [junedomingo/react-native-rename#13]
On windows, it partially fails with this message:  "Error: Command failed: rm -rf ./ios/build && rm -rf ./android/.gradle && rm -rf ./android/app/build && rm -rf ./android/build"

This is because rm does not exists on windows (unlike linux or osx (unix)). it is replaced by rmdir (or rd). So you shoud use "rd /s /q" instead of "rm -rf" when run on windows.
And also invert the path slashes (on windows it would be rm -rf .\android\.gradle for example)

One other thing, when chaining commands like this (with &&), if one fails, all commands after that would not be executed. So if /ios/build does not exists for example, android/.gradle, /android/app/build and /android/build would not be deleted. So you should execute these commands in seperate command calls so that one failing do not impact all the others...

Except from that, good package, saved me some time compared to doing it by hand ;)

**Comment by junedomingo** [comment]
Hey @ramsestom , Thank you for pointing it out and for the tips.
Done fixing it! 😉
