### ISSUE TITLE
Not working with us

### ISSUE THREAD

**Issue by rohi22** [junedomingo/react-native-rename#130]
Dear
We have tried to change the package name. For android, it worked.
But for iOS, it is not working while I tried to change the package name, iOS folders names, and third party library files "dot exe workspace"
We tried to change forcefully and the app didn't work.

Does any solution please its urgent?

**Comment by vomchik** [comment]
@rohi22 Could you try the latest version?

**Comment by beqramo** [comment]
@vomchik it happens to me too, I'm using the latest version and also the react-native 0.64 version. I'm running it with npx, I  found some solutions here but none of them worked for me

**Comment by beqramo** [comment]
it called PizzaName, and I want to rename it to TwoWallet

**Comment by beqramo** [comment]
@vomchik 
 android is renamed with its own bundle id but on ios just podfile targets is changing

**Comment by beqramo** [comment]
I checked permissions too for files and directories and everything is normal

**Comment by vomchik** [comment]
do you have this file? `ios/PizzaName.xcworkspace`

**Comment by beqramo** [comment]
yes

**Comment by vomchik** [comment]
@beqramo on an initial project I can rename `PizzaName` to `TwoWallet`

![image](https://user-images.githubusercontent.com/732085/115399808-3eef6a00-a1f1-11eb-8249-a58e179ce537.png)
![image](https://user-images.githubusercontent.com/732085/115399918-5890b180-a1f1-11eb-8122-05f4b793eb4c.png)

**Comment by beqramo** [comment]
hmm, maybe the problem is that I'm using  https://github.com/infinitered/ignite
and this isn't supported?

**Comment by vomchik** [comment]
oh, will try to check it later

**Comment by beqramo** [comment]
I checked the library above and there is no issue about rename, I will create a fresh project too with ignite and will try to rename

**Comment by beqramo** [comment]
it worked on a fresh project but I don't understand why it doesn't work on the old one. Okay, I will continue from the fresh project anyway, thanks
