### ISSUE TITLE
Dont Work - SyntaxError

### ISSUE THREAD

**Issue by caiomendes23** [junedomingo/react-native-rename#132]
When i run this command, i receive erro...

<img width="763" alt="Captura de Tela 2021-04-13 às 08 32 03" src="https://user-images.githubusercontent.com/51244362/114545770-bc840a80-9c32-11eb-806d-627c4e074b4e.png">

Pls...help need!!

**Comment by vomchik** [comment]
Please check your `app.json` file. Looks like it, not a valid JSON.

**Comment by vomchik** [comment]
Also, you can't use dash symbol in a  bundle id

**Comment by caiomendes23** [comment]
Thanks for resolve my issue!
