### ISSUE TITLE
Error: Can't find an ios path or project. Make sure that the ios project path and property 'name' in app.json the same

### ISSUE THREAD

**Issue by kaanyenigul** [junedomingo/react-native-rename#133]
Hi there,
Version 2.8.0 returns a  error 
**Error: Can't find an ios path or project. Make sure that the ios
project path and property 'name' in app.json the same.**

for **npx react-native-rename "AppName" -b com.xxx.xxx**

I was downloaded 2.7.0 version and it works fine.

**Comment by birtandincer** [comment]
thanks for info🙏🏻successull

**Comment by vomchik** [comment]
Make sure that all names matched

<img src="https://user-images.githubusercontent.com/732085/114676202-bfa1f800-9d11-11eb-9d63-6550192a624f.png" width="300" height="300">

**Comment by kaanyenigul** [comment]
You'r right, thank you!

**Comment by frankfuu** [comment]
Thanks!
