### ISSUE TITLE
Trying to execute in Windows Prompt

### ISSUE THREAD

**Issue by duduccosta** [junedomingo/react-native-rename#134]
Hi,

I've created an expo bare workflow project.
Trying to execute with CMD Prompt.

Error message:
Error: Can't find an ios path or project. Make sure that the ios project path and property 'name' in app.json the same.

**Comment by vomchik** [comment]
@duduccosta maybe this can help for you  https://github.com/junedomingo/react-native-rename/issues/133

**Comment by duduccosta** [comment]
> @duduccosta maybe this can help for you #133

Thank you! It worked!
