### ISSUE TITLE
Android files has been removed

### ISSUE THREAD

**Issue by duduccosta** [junedomingo/react-native-rename#135]
I noticed that my android files has been removed.

android/app/src/debug/java/com/appsocio/ReactNativeFlipper.java
android/app/src/main/java/com/appsocio/MainActivity.java
android/app/src/main/java/com/appsocio/MainApplication.java
android/app/src/main/java/com/appsocio/generated/BasePackageList.java

Project created with Expo Bare workflow.
Using latest version of this package.

Old BundleId = "com.appsocio"
New BundleId = "com.qualitysys.0009"

Does anyone know why?

**Comment by duduccosta** [comment]
I've done some tests.
I think the problem is because "git mv -k" is not copiyng files, only folders.

**Comment by duduccosta** [comment]
I found the problem.

My folder is under a git repository, so when you check the condition:
`gitMove.code === 128`

This error code is wrong in my case, because 128 is not bad source.
I didn't found the correctly error code for 'bad source', but if someone else find it, just release a new version with the correctly code.

**Comment by joaosouz4dev** [comment]
same here

**Comment by joaosouz4dev** [comment]
@duduccosta can u help me?

**Comment by joaosouz4dev** [comment]
@junedomingo can u help me, here?

**Comment by joaosouz4dev** [comment]
@duduccosta thank u https://github.com/duduccosta/react-native-rename

**Comment by vomchik** [comment]
I have removed using a git for moving files as it leads to bugs. Now after moving, we run `git add .`
Please use the latest version `v2.9.0` and let me know if the fix works for you.

@duduccosta Btw you have a invalid bundle id
![image](https://user-images.githubusercontent.com/732085/120233644-fa7ad380-c25e-11eb-9136-30c8a4b1102a.png)
https://developer.android.com/studio/build/application-id

**Comment by vomchik** [comment]
@duduccosta You can't use numbers in bundle id

**Comment by Nikostito** [comment]
This bug is still present on 2.9.0 @vomchik

**Comment by pedenys** [comment]
Same happened to me while running `npx react-native-rename newname -b com.newname.newnameAndsomething` (uppercase in the middle of the third word + two dots) with 2.9.0. 

Also, I already had moved the files listed in the original post to a correct path (from `android/app/build/src/main/com/oldname` to `android/app/build/src/main/com/newname/Andsomethingelse`).

**Comment by junedomingo** [comment]
Closing, please check v3.
