### ISSUE TITLE
Android app: Error: Can't find an ios path or project. [...]

### ISSUE THREAD

**Issue by matthieuuu** [junedomingo/react-native-rename#136]
Hello!

Currently I'm only developing on Android target, and since version > 2.7.1, react-native-rename is throwing the following error: 

`Error: Can't find an ios path or project. Make sure that the ios project path and property 'name' in app.json the same.`

Is there any way the package does NOT check for ios files since I don't have those?

Thanks!

**Comment by selimabatay** [comment]
I have the same problem

**Comment by ElpayetSupervan** [comment]
same here

**Comment by emmanuelfrancis** [comment]
Tried @2.7.1 and it worked.

**Comment by vomchik** [comment]
Fixed in v2.8.2
