### ISSUE TITLE
Android: The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed

### ISSUE THREAD

**Issue by Satya5614** [junedomingo/react-native-rename#139]
This happens only on Android (RN version 0.64.1). The reason is that when we rename a project the android debug folder des does not get renamed. The solution for this issue I found it the following two comments

https://github.com/facebook/flipper/issues/1253#issuecomment-650134944
https://github.com/facebook/flipper/issues/1253#issuecomment-663423999

I will try to fix it and create a PR here.

**Comment by junedomingo** [comment]
Closing, please check v3.
