### ISSUE TITLE
Android folder doesn't change

### ISSUE THREAD

**Issue by nguyenvantruong17** [junedomingo/react-native-rename#141]
Current: It still keeps the name **_rnbasecore_**
Expect: Rename to  **_somaletran_**

![Screen Shot 2021-06-04 at 15 15 55](https://user-images.githubusercontent.com/18642063/120769956-d57cae00-c547-11eb-9442-80ee92e812a0.png)

**Comment by vomchik** [comment]
Did you change the name app only or bundle id also?

**Comment by nguyenvantruong17** [comment]
> Did you change the name app only or bundle id also?

@vomchik I just changed the name app

**Comment by vomchik** [comment]
When you change an app name, the path can't change as is dependent on the bundle id
