### ISSUE TITLE
The react-native-rename command is not working depending on the directory it is executed from

### ISSUE THREAD

**Issue by Nikostito** [junedomingo/react-native-rename#142]
I don't know if this is because of folder permissions, but on Ubuntu 20.04, the command isn't working when executed within any subfolder of the /home/ directory. It says it modifies files but no files are modified. On the contrary if I first copy the project folder to /tmp and then execute the react-native-rename, it works as expected. Any input on this would be greatly appreciated!

**Comment by junedomingo** [comment]
Closing, please checkout v3. Let me know if there are any issues
