### ISSUE TITLE
Renaming the app with a <space> between the name doesn't work!

### ISSUE THREAD

**Issue by husseinaltaaf** [junedomingo/react-native-rename#143]
For e.g: if i rename my app as "Tech Tutorial"
It changes my app's name to "Tech"!

**Comment by mariansam** [comment]
What's the exact command you ran? Keep in mind that the command line uses spaces as argument separators, so you have to put "Tech Tutorial" in quotes like this: `react-native-rename "Tech Tutorial"`

**Comment by Arcalise08** [comment]
> What's the exact command you ran? Keep in mind that the command line uses spaces as argument separators, so you have to put "Tech Tutorial" in quotes like this: `react-native-rename "Tech Tutorial"`

I think its obvious he used the quotes. he even did it in the title.

**Comment by MasterRedStorm** [comment]
I had the exact same problem. My solution was to downgrade to "react-native-rename": "2.8.2",

**Comment by Adnan-Bacic** [comment]
im pretty sure you arent supposed/allowed to have spaces in project names. just like you dont have spaces in folder names in your project.

**Comment by mariansam** [comment]
Thanks for pinging, I'm on react-native-rename 2.9.0 and `react-native-rename 'Some Three Words'` worked for me a few days ago. I'm using Expo and I had a problem with the URI scheme, so I created a new one using `npx uri-scheme add somethreewords` and everything works now.

**Comment by junedomingo** [comment]
Closing, please check v3.
