### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by KennyGoi** [junedomingo/react-native-rename#146]
**Affected files**:
react-native-rename/tests/rn-versions/0.64/ios/TestApp64/Info.plist
`1: <?xml version="1.0" encoding="UTF-8"?>`

**Risks**:
ATS prevents accidental disclosures, provides secure default behavior, and is easy to adopt.
App Transport Security (ATS) enforces best practices in the secure connections between an app and its back end.

**Comment by junedomingo** [comment]
Closing, please check v3.
