### ISSUE TITLE
Cyrillic letters in app's name break iOS build

### ISSUE THREAD

**Issue by CyxouD** [junedomingo/react-native-rename#147]
When we use `react-native-rename` command with Cyrillic letters in a new app's name (like `npx react-native-rename "Название_с_кириллицей"`), we break iOS build. Android works OK. I believe it is the issue with `XCode` but I think it's worth to note it in `README` and warn user after running this command.

My solution for now is to run `react-native-renamed` command with the name in Latin and rename app's display name manually for iOS (`Display Name` in `XCode`'s `General` settings) and Android (`app_name` string in `strings.xml`)

**Comment by junedomingo** [comment]
Closing, please check v3.
