### ISSUE TITLE
colors.js LIBERTY LIBERTY LIBERTY crashing

### ISSUE THREAD

**Issue by frankfuu** [junedomingo/react-native-rename#148]
I think this project is affected by the recent `colors` package corruption. 

Read more here - https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

Is there a way around it?

**Comment by davux** [comment]
This is related to https://github.com/Marak/colors.js/issues/285.

The fix is to use colors v1.4.0 explicitly.

**Comment by davux** [comment]
To clarify things: this is a workaround to "unbreak" react-native-rename until a new official repo for colors.js is set up.

**Comment by davux** [comment]
The problem should be fixed now (with no PR needed), as npm [unpublished the offending versions](https://github.com/Marak/colors.js/issues/317#issue-1098535594). I think you can close it, @frankfuu.

**Comment by frankfuu** [comment]
Thanks @davux
