### ISSUE TITLE
Showing Trash string when while running 

### ISSUE THREAD

**Issue by rk-maker** [junedomingo/react-native-rename#151]
install properly but when i run the command it goes in infinite loop and show this string or trash value 

i n
̂g t
̩e
̟st
̆i
̨ng
̣ 
̝te
̻st
̩i
̲ng
͋ 
̲teͯ̌̇
̏ st
͢i
͞n
̞g 
t e šͮ̊
̐t
̑in
̓g  
͗t
̹es
͐ t
̩in
̘g  
҉t
͚e
̜st 
̼i
͍n
̝g t 
̭e
̦st
ͨin
̈g 
́t
̎e
͒s ҉̮̯
̺t 
͙in̅̾ͮ
̚g ̈̔͆
͊te
̜s t
̰in
̭g 
̦t
̳es 
҉ti
̬n
̩g
te
̣st
̼i
͇n
̳g
̮ t
̱e
͔st
̄in
g t
̗es
̋t
̃i 
͕n
̹g
̖ t
͔es ҉̗̞
̘t
̯in
̪g
͖ 
͖t
̣es
͎t i
̥ng
̼ 
͕t es
́ti
ͥn 
̼g 
͚t
͉e
͇sti
ͥ n
̰g
te͐̔
̓s
̹t 
͎i n
̷g
̥ t
͝e
͘s ҉̢ t
̴i
̟ng
̳ 
͕te
̙s t
̝i ҉ n
̹g
͎ 
̩t 
es
̳ti
̢n
̟g 
̥ t
̮es̑͋
̂t
̀i
̘n
̦g
̝ 
̲t
̺e 
̞st
͖i
ͅn
̼g 
̷t
̜es
ͫ t 
͍i n
͐ g

**Comment by gustavojg** [comment]
This is a colors dependency issue.
https://twitter.com/midudev/status/1480482336370302980?t=kXAixdGj2q5PfiNHDhe6Jg&s=19

**Comment by junedomingo** [comment]
Closing, please check v3
