### ISSUE TITLE
renaming doesnt work with ios

### ISSUE THREAD

**Issue by Yasir5247** [junedomingo/react-native-rename#152]
![photo_2022-01-17_10-35-13](https://user-images.githubusercontent.com/472971/149719119-687bd762-bb3d-4024-9352-62e3980abce2.jpg)

renaming the project still doesnt work for me. i tried with windows, and with a friends computer. still ios directory folders name starts with RNNStarter. what am i missing here.

from the above screen shot. does it mean i have to manually rename folder name's in the ios directory to match the name in the app.json file?

my app.json file.
{
"name": "Aiminaabee",
"displayName": "Aiminaabee"
}

**Comment by obernardovieira** [comment]
Hi

I'm having the same issue. Any idea?

**Comment by Ppang0405** [comment]
yes, I have the same issue.

**Comment by Ppang0405** [comment]
does anyone know how to fix it?

**Comment by junedomingo** [comment]
Closing, please check v3
