### ISSUE TITLE
Unable to rename react-native init typescript project

### ISSUE THREAD

**Issue by lyqht** [junedomingo/react-native-rename#153]
I'm trying out the package to rename a RN project is created from the typescript template by running

```
npx react-native-rename "NewApp"
```

however, I encountered an error that says the following

```
Need to install the following packages:
  react-native-rename
Ok to proceed? (y) y
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
Directory should be created using "react-native init"
```

I'm pretty sure it was created with react-native init, so I'm not sure what is the actual error.

**Comment by junedomingo** [comment]
Closing, please check v3
