### ISSUE TITLE
Not compatible with RN 0.68.0

### ISSUE THREAD

**Issue by makozlo** [junedomingo/react-native-rename#156]
When creating a new project with `npx react-native init [originalProjectName]` and then subsequently running `npx react-native-rename [newProjectName]`, the project won't run correctly in the iOS simulator and it throws the following error (image also attached to this post):

```
[originalProjectName] has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```
<img width="446" alt="CleanShot 2022-04-11 at 16 14 26@2x" src="https://user-images.githubusercontent.com/10499188/162834548-f3bf79de-66b3-42fe-8153-218946ab3916.png">

**Comment by sametpalitci** [comment]
Hello, open your `AppDelegate.mm` file. Find `RCTAppSetupDefaultRootView` Change your project name after @.
e.g.   `UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"projectName", nil);`
Solved for me, happy coding.

**Comment by makozlo** [comment]
Thanks @sametpalitci , this worked!
