### ISSUE TITLE
 Invariant Violation: "AppName" has not been registered. This can happen if:

### ISSUE THREAD

**Issue by kabundege** [junedomingo/react-native-rename#158]
# Description?
 After running  `npx react-native-rename "old_app_name" -b com.packagename`, everthing is updated but one line in the MainActivity. `see the screenshot below`

# Screenshot 
![Screen Shot 2022-05-29 at 08 37 15](https://user-images.githubusercontent.com/50319826/170855570-3693e8e4-4a12-4883-af20-c2edda7c7191.png)

# Fix (Work-around)
update that string value `old_app_name` to the new desired app name, used above `com.packagename`

**Comment by junedomingo** [comment]
Closing, please check v3

**Comment by methineeinkan** [comment]
Check the App name in MainActivity at getMainComponentName function, app.json, and package.json it will same in these 3 places.
