### ISSUE TITLE
IOS ONlLY: Invariant Violation: "AppName" has not been registered. This can happen if

### ISSUE THREAD

**Issue by vikas-chhabra** [junedomingo/react-native-rename#159]
In **ios>appName>AppDelegate.mm**

In **RCTAppSetupDefaultRootView** change old_app_name to new_app_name

npx react-native-rename "new_app_name" updated new_app_name everywhere except this one instance. 

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/26916970/170891251-bb8cfc9a-7284-4ee3-8467-df1d14195eb7.png">

**Comment by jspizziri** [comment]
FYI, this is only an issue RN > 0.67. [In RN `0.68`, `AppDelegate.m` was moved to `AppDelegate.mm`](https://react-native-community.github.io/upgrade-helper/?from=0.67.4&to=0.68.0).

**Comment by jspizziri** [comment]
Looks like there's a PR out to address this already https://github.com/junedomingo/react-native-rename/pull/157

**Comment by shyamalVixplor** [comment]
> In **ios>appName>AppDelegate.mm**
> 
> In **RCTAppSetupDefaultRootView** change old_app_name to new_app_name
> 
> npx react-native-rename "new_app_name" updated new_app_name everywhere except this one instance.
> 
> <img alt="image" width="1076" src="https://user-images.githubusercontent.com/26916970/170891251-bb8cfc9a-7284-4ee3-8467-df1d14195eb7.png">

You saved my day:)

**Comment by baha-udin** [comment]
https://github.com/junedomingo/react-native-rename/issues/159#issue-1251990267
thanks bro, work in 0.68.2 version

**Comment by wanderlust252** [comment]
you saved my day. Thank you sir!

**Comment by junedomingo** [comment]
Closing, please check v3

**Comment by muhammadashariabdillah24** [comment]
Just to add, if you have changed the name of the application but it still displays an error, my suggestion is also to change the name of the application in the app.json file
<img width="1064" alt="Screen Shot 2023-10-25 at 10 04 58" src="https://github.com/junedomingo/react-native-rename/assets/84664072/13b79a0a-d61e-4523-81a5-f26bfbf8b940">
