### ISSUE TITLE
 valid identifier name (alphanumeric and space)

### ISSUE THREAD

**Issue by hszeto** [junedomingo/react-native-rename#16]
I want to change my app name to lets-chat. When I run 

```react-native-rename "lets-chat"```

I got the following error:

```"lets-chat" is not a valid name for a project. Please use a valid identifier name (alphanumeric and space).```

How should I deal with the dash?

**Comment by junedomingo** [comment]
`-` (dashes are not allowed) at the moment

**Comment by junedomingo** [comment]
but you can do `"lets chat"`

**Comment by voxspox** [comment]
also check https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
