### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by talha7t** [junedomingo/react-native-rename#169]
I get the error 

> Unexpected token '?'

 when running `npx react-native-rename "App name" -b "bundleId"`. I have run the command both locally and globally, but I still get this error.

node version: 12.22.12
npm version: 6.14.16
react-native version: 0.68.1 
react-native-rename version: 3.2.0

**Comment by junedomingo** [comment]
Hi @talha7t , you need to use node version >= 16 for now
