### ISSUE TITLE
Podfile

### ISSUE THREAD

**Issue by Twinski** [junedomingo/react-native-rename#17]
Hey June! Super-nice tool. Saves a lot of work when duplicating my repo to bootstrap RN projects.
I'll buy you a beer when you're in Belgium.

On topic:
It seems the target-name doesn't get updated in "ios/Podfile". Might be important to rename the target there as well. 

Thanks!

**Comment by junedomingo** [comment]
Thanks for the kind words @Twinski ! 
beers! that would  be awesome 🍻
