### ISSUE TITLE
Error: Dynamic require of "normalize-path" is not supported

### ISSUE THREAD

**Issue by KenAndSean** [junedomingo/react-native-rename#173]
Anyone can help me?
I just init a new project with react-native cli.
and then use this command, npx react-native-rename "new_name".
I got this error.

Package Version:
react-native: 0.70.6
react: 18.1.0

**Comment by junedomingo** [comment]
Hi @KenAndSean for safety reasons, you need to git init your app project so you can always revert to the original state when an issue occurs during renaming.

Steps you can do:
```bash
git add .
git commit -m "Initial commit"
```

You may now proceed to rename it
```bash
npx react-native-rename@3.2.6 "Travel App"
```

**Comment by milindgoel15** [comment]
Hey @junedomingo , can you please add this to the documentation since its a necessary step anyway.
