### ISSUE TITLE
Error: Cannot find module 'node:process'

### ISSUE THREAD

**Issue by huukhuong** [junedomingo/react-native-rename#177]
code: 'MODULE_NOT_FOUND',
  requireStack: [
    '########/node_modules/react-native-rename/lib/index.js'
  ]

**Comment by junedomingo** [comment]
Hi @huukhuong , what's your node version?

**Comment by huukhuong** [comment]
> Hi @huukhuong , what's your node version? 

Thank you, I switched from node 14 to node 16 and it works fine
