### ISSUE TITLE
"Not Renamed"

### ISSUE THREAD

**Issue by Saalim95** [junedomingo/react-native-rename#179]
<img width="863" alt="Screenshot 2023-01-13 at 12 41 56 PM" src="https://user-images.githubusercontent.com/19245026/212259493-c220deff-328f-43d0-bf5f-9cdaefcd20a7.png">

**Comment by pataiadam** [comment]
Maybe you're encountering similar issues as I described in [this comment](https://github.com/junedomingo/react-native-rename/issues/185#issuecomment-1396120033).

**Comment by junedomingo** [comment]
Hi @ Saalim95, can you confirm if it's not similar to #185? I can see that you may be trying to rename it the second time.
if it's not, can you share the whole screenshot?
