### ISSUE TITLE
This is not a git repository

### ISSUE THREAD

**Issue by criss02-cs** [junedomingo/react-native-rename#189]
**Describe the bug**
When I try to rename my app, i gave me: This is not a git repository

**To Reproduce**
1. create a new project
2. install react-native-rename
3. run npx react-native-rename "NameApp" -b "bundle"

**Expected behavior**
I want to change the name and package of my app, but i can't

**Screenshots**

**Environment (please complete the following information):**
 - operating system: Windows 111
 - npm version: 8.14.0
 - node version: 16.16.0
 - react-native-rename version: 3.2.10
 - react-native version: 0.71.1

**Additional context**

**Comment by junedomingo** [comment]
Hi @criss02-cs, please refer to this comment https://github.com/junedomingo/react-native-rename/issues/173#issuecomment-1374331270

**Comment by cas8398** [comment]
> Hi @criss02-cs, please refer to this comment [#173 (comment)](https://github.com/junedomingo/react-native-rename/issues/173#issuecomment-1374331270)

because i renamed with cmd i got an error, This is not a git repository. i followed this instruction, i opened github app, created new repo with this directory. then i opened git app, cd to app directory and ran react-native-rename and rename it properly.

i think, good if you add this to readme.md
