### ISSUE TITLE
Accented words not allowed

### ISSUE THREAD

**Issue by netojose** [junedomingo/react-native-rename#19]
On try rename project with accented words, the action is not allowed:

![Error -> https://image.prntscr.com/image/FvQd69ngSGKI-5TEOZaf8A.png](https://image.prntscr.com/image/FvQd69ngSGKI-5TEOZaf8A.png "Error")

[Screenshot error](https://image.prntscr.com/image/FvQd69ngSGKI-5TEOZaf8A.png)

**Comment by junedomingo** [comment]
Hi @netojose , it's not supported at the moment

**Comment by netojose** [comment]
Ok, thanks!
