### ISSUE TITLE
Bundle Identifier Not Valid

### ISSUE THREAD

**Issue by redreceipt** [junedomingo/react-native-rename#190]
**Describe the bug**

Says I can't use an iOS bundle identifier with a hyphen in it because "it's not valid" but that's not true. My app has a hyphen in it. So I can't use the script to build my app.

**To Reproduce**

`react-native-rename TestApp --iosBundleID com.org.test-app`

**Expected behavior**

It should work

**Screenshots**

**Environment (please complete the following information):**
 - operating system: MacOS
 - npm version: 8
 - node version:16
 - react-native-rename version: 3.2.10
 - react-native version: 67

**Additional context**

**Comment by junedomingo** [comment]
Thanks, @redreceipt for pointing it out. Fixed in v3.2.11

**Comment by redreceipt** [comment]
here's another one, underscores too https://github.com/junedomingo/react-native-rename/pull/236
