### ISSUE TITLE
Doesn't work on linux

### ISSUE THREAD

**Issue by truckingsim** [JuneDomingo/react-native-rename#2]
The problem lies in the first line of `index.js`:

```js
#!/usr/bin/env node --harmony
```

If you run this on linux you will get this error:

```
/usr/bin/env: ‘node --harmony’: No such file or directory
```

On linux (in both bash and zsh at least) you can't pass arguments and use `/usr/bin/env`.  When using `/usr/bin/env` on linux, with arguments, it attempts to run `'node --harmony'` as one program rather than `node` as the program with the `--harmony` argument.

This isn't a PR as I don't really have a solution for you as there isn't much of a work around this. I do question what do you need the `--harmony` argument for?

If it's not truly needed and you can work around it somehow then this would work fine on linux.

**Comment by truckingsim** [comment]
Also forgot to add this only happens with shebang env (`#!/usr/bin/env`) you won't see this problem if you run `/usr/bin/env node --harmony` from the command line.  That will work, but if you have a file and you use the shebang version you will run into this problem.

**Comment by prijindal** [comment]
Manually removing the harmony tag solves the problem

**Comment by truckingsim** [comment]
@prijindal for sure, I just don't know why it was there to start with.

**Comment by JuneDomingo** [comment]
Hey guys, thanks for reporting. issue has been fixed.  the `--harmony` tag is required by `commander` package because i'm not using babel back then and i didn't know that this can cause problem for other OS.
