### ISSUE TITLE
I just want to change the package name.

### ISSUE THREAD

**Issue by bloggerklik** [junedomingo/react-native-rename#202]
I just want to change the package name. Which command should I use for this?

**Comment by junedomingo** [comment]
Hi @bloggerklik! you can try `npx react-native-rename@latest "current_name" -b "bundle_identifier"` that if you want to change bundle/package name on both platforms.

But if you only need to change the package name on android you can use: 
`npx react-native-rename@latest "current_name" --androidBundleID "new_package_name_here"`

and for ios, you can use:
`npx react-native-rename@latest "current_name" --iosBundleID "new_bundle_id_here"` 

Let me know if this helps.

**Comment by bloggerklik** [comment]
I applied it that way too, but there are "NOT RENAMED" and "NOT UPDATE"s. Should I ignore it? Thanks.

`PS C:\Users\***\Desktop\***> npx react-native-rename "***" -b "***"
ios\*** NOT RENAMED
ios\***\***.entitlements NOT RENAMED
ios\***\***Release.entitlements NOT RENAMED
ios\***-tvOS NOT RENAMED
ios\***-tvOSTests NOT RENAMED
ios\***.xcworkspace NOT RENAMED
ios\***Tests NOT RENAMED
ios\***Tests\***Tests.m NOT RENAMED
ios\***.xcodeproj NOT RENAMED
ios\***.xcodeproj\xcshareddata\xcschemes\***-tvOS.xcscheme NOT RENAMED
ios\***.xcodeproj\xcshareddata\xcschemes\***.xcscheme NOT RENAMED
ios\***-Bridging-Header.h NOT RENAMED
ios\Podfile NOT UPDATED (2 matches)
ios\***\[AppDelegate.mm](http://appdelegate.mm/) NOT UPDATED (1 match)
ios\***.xcodeproj\project.pbxproj NOT UPDATED (93 matches)
ios\***.xcodeproj\xcshareddata\xcschemes\***.xcscheme NOT UPDATED (10 matches)
ios\***Tests\***Tests.m NOT UPDATED (0 matches)
ios\***.xcodeproj\project.pbxproj NOT UPDATED (52 matches)
ios\***Tests\***Tests.m NOT UPDATED (2 matches)
ios\***.xcodeproj\xcshareddata\xcschemes\***.xcscheme NOT UPDATED (2 matches)
ios\***.xcodeproj\project.pbxproj UPDATED (25 matches)
ios\***.xcodeproj\project.pbxproj UPDATED (0 matches)
ios\***\LaunchScreen.storyboard NOT UPDATED (2 matches)
ios\***\Info.plist UPDATED
android\app\src\debug\java\***\***\*** RENAMED
android\app\src\main\java\***\***\*** RENAMED
android\app\src\release\java\***\***\*** RENAMED
android\settings.gradle NOT UPDATED (1 match)
android\app\src\main\java\***\***\***\MainActivity.java NOT UPDATED (1 match)
android\app\build.gradle NOT UPDATED (0 matches)
android\app\build.gradle UPDATED (2 matches)
android\app\src\debug\java\***\***\***\ReactNativeFlipper.java UPDATED (1 match)
android\app\src\release\java\***\***\***\ReactNativeFlipper.java UPDATED (1 match)
android\app\src\main\java\***\***\***\MainActivity.java UPDATED (1 match)
android\app\src\main\java\***\***\***\MainApplication.java UPDATED (1 match)
android\app\src\main\AndroidManifest.xml NOT UPDATED (0 matches)
android\app\src\main\res\values\strings.xml UPDATED
index.js NOT UPDATED (0 matches)
package.json NOT UPDATED (2 matches)
app.json NOT UPDATED (6 matches)
Done removing builds.

SUCCESS! 🎉 🎉 🎉 Your app has been renamed to "***".

- Make sure to check old .xcodeproj and .xcworkspace in ios folder, please delete them manually.
- Please make sure to run "npx pod-install" and "watchman watch-del-all" before running the app.

If you like this tool, please give it a star on GitHub: [https://github.com/junedomingo/react-native-rename](https://github.com/junedomingo/react-native-rename)`

**Comment by junedomingo** [comment]
Yes, just ignore them.
