### ISSUE TITLE
Cannot find module 'node:process'

### ISSUE THREAD

**Issue by zaheerkhalil321** [junedomingo/react-native-rename#203]
Cannot find module 'node:process'
Require stack:
- /Users/mzaheer/Downloads/Working-Projects/arar_customer_app/node_modules/react-native-rename/lib/index.js

**Comment by junedomingo** [comment]
@zaheerkhalil321 I need some info

Environment (please complete the following information):

operating system:
npm version:
node version:
react-native-rename version:
react-native version:

**Comment by junedomingo** [comment]
@zaheerkhalil321 try updating to the latest node version. 
and try `npx react-native-rename@latest "new_name" -b "bundle_identifier"`.
