### ISSUE TITLE
Please provide path and content string using "-p [value]" or "--pathContentStr [value]" option to be used in renaming the folders, files and their contents.

### ISSUE THREAD

**Issue by Sohnyneo** [junedomingo/react-native-rename#206]
Can't rename. Says "Please provide path and content string using "-p [value]" or "--pathContentStr [value]" option to be used in renaming the folders, files and their contents."

**To Reproduce**
1. npx react-native-rename@latest "APPNAME" -b com.XXXX.XXX
2. or: npx react-native-rename "APPNAME" --androidBundleID com.XXXX.XXX --iosBundleID com.XXXX.XXX

**Comment by Sohnyneo** [comment]
It usually worked with 
npx react-native-rename "app name"

But today, it is not even working with the above simple command.

```
$ npx react-native-rename "igs"
Please provide path and content string using "-p [value]" or "--pathContentStr [value]" option to be used in renaming the folders, files and their contents.
example: react-native-rename "igs" -p "[value]"
```

**Comment by junedomingo** [comment]
Hi @Sohnyneo , it means "igs" is too short for folders and files name. try `npx react-native-rename "igs" -p "IgsApp"` something like that

**Comment by macrozone** [comment]
@junedomingo why is there a minimum length? 

The default react-native creates folders named "app". Its now impossible to use this tool just to change the packagename. Can this limit be removed?  I don't see why it is there in the first place. Is there a reason for that?
