### ISSUE TITLE
Build doesn't work after rename

### ISSUE THREAD

**Issue by AnthonyLamot** [junedomingo/react-native-rename#21]
I really liked this package and just ran it. 

However, after I've renamed my app, and I run `cd android && ./gradlew assembleRelease`to do another build, I get an error:

```
2 errors
:app:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
``` 

Any idea how to resolve this?

**Comment by AnthonyLamot** [comment]
One observation I made in the meantime: There was a folder with the older name that didn't get cleared.

`rm -rf android/app/src/main/java/com/OldProjectName`

**Comment by AnthonyLamot** [comment]
Okay, found the issue, though you may want to update this module!

In `/Users/UserName/AppName/rn/android/app/src/main/java/com/AppName/MainActivity.java`, line 13 got updated to `retuAppName "AppName";`, instead of `return "AppName";`.

Hope that helps!

**Comment by sillygoose4u** [comment]
Why wouldn't it let me have space in between my app name?

**Comment by trangcongthanh** [comment]
I can't build my app after rename too. Got same error like @sillygoose4u's comment.

**Comment by mycodeself** [comment]
Hey, 

first of all thank you for this awesome tool!

I was with the same issue using react-native-rename@2.2.2, after rename the app the build is succesfully but the application doesnt start. 

The problem was that my "MainActivty.java" the package reference name of last item was UpperCase, example:

`package com.company.MyApp;`

i change it to 
`package com.company.myapp;`

and it works like a charm! 

hope it helps to you!

**Comment by LorandP** [comment]
Also you can try running `./gradlew clean` in your android folder.

**Comment by ajcrites** [comment]
Please try with version 2.3.0. Open another issue if it persists.

**Comment by moustaouiSalaheddine** [comment]
if you have google-services.json change your package in inside google-services.json
if work : generate a new google-services.json
