### ISSUE TITLE
Regular Expression Denial of Service 

### ISSUE THREAD

**Issue by renehauck** [junedomingo/react-native-rename#23]
After I installed your package, i get this error-message (yarn):

nsp check
(+) 1 vulnerabilities found
┌───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                                                                                   │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ minimatch                                                                                                              │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ CVSS          │ 7.5 (High)                                                                                                             │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.2.14                                                                                                                 │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ <=3.0.1                                                                                                                │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Patched       │ >=3.0.2                                                                                                                │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Path          │ generator-beagle@0.0.0 > react-native-rename@2.1.2 > replace@0.3.0 > minimatch@0.2.14                                  │
├───────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/118                                                                                 │
└───────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by junedomingo** [comment]
Hi @renehauck ,thanks for reporting. may i ask what's you environment version (NodeJS & yarn)?

**Comment by renehauck** [comment]
I'd be glad to :smiley:  
I'm using yarn.
This should be the fix:

> Regular Expression Denial of Service
> Module: minimatch
> ....

> Remediation
> 
> Updated to version 3.0.2 or greater

**Comment by renehauck** [comment]
fixed :+1:
