### ISSUE TITLE
If new name is 3 chars will fail

### ISSUE THREAD

**Issue by flyskywhy** [junedomingo/react-native-rename#234]
**Describe the bug**
If new name is 3 chars e.g. "xyz" , will got:
```
Please provide path and content string using "-p [value]" or "--pathContentStr [value]" option to be used in renaming the folders, files and their contents.
example: react-native-rename "xyz" -p "[value]"
```

if more than 3 chars e.g. "xyza" will be good.

**To Reproduce**
1. npx react-native-rename "xyz" -b com.flyskywhy.xyz

**Expected behavior**
to runs well.

**Environment (please complete the following information):**
 - operating system: Linux Ubuntu
 - npm version: 8.11.0
 - node version: v16.16.0
 - react-native-rename version: 3.2.12
 - react-native version: 0.70.5

**Comment by junedomingo** [comment]
@flyskywhy please checkout v3.2.13 now
