### ISSUE TITLE
If old and new name is similar, then new name will be wrong in many place

### ISSUE THREAD

**Issue by flyskywhy** [junedomingo/react-native-rename#235]
**Describe the bug**
If old and new name is similar e.g. old is "xyza" and new is "xyzab", then will be wrong "xyzabb" in
```
android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
android/app/src/main/jni/MainComponentsRegistry.h
app.json
package.json
```
and
```
ios/xyza.xcodeproj/xcshareddata/xcschemes/xyza.xcscheme
```
will be wrong `xyza.xcscheme` (should be `xyzab.xcscheme`):
```
ios/xyzab.xcodeproj/xcshareddata/xcschemes/xyza.xcscheme
```

**To Reproduce**
1. old is `npx react-native-rename "xyza" -b com.flyskywhy.xyza`
2. new is `npx react-native-rename "xyzab" -b com.flyskywhy.xyzab`

**Expected behavior**
runs well.

**Environment (please complete the following information):**
 - operating system: Linux Ubuntu
 - npm version: 8.11.0
 - node version: v16.16.0
 - react-native-rename version: 3.2.12
 - react-native version: 0.70.5

**Comment by junedomingo** [comment]
Hi @flyskywhy the trick is to rename to a different name first, e.g if your old name is "xyza" then just use "awesomeapp", after that, then use "xyzab".

**Comment by flyskywhy** [comment]
Ok, I will use the trick preferentially for now, thanks!
