### ISSUE TITLE
Please add support for other languages

### ISSUE THREAD

**Issue by eladcandroid** [junedomingo/react-native-rename#26]
For example: 

After running:
`react-native-rename "מקרא מבואר" -b com.eladcohen.mikra`

(With Hebrew characters)

I've got:
"מקרא מבואר" is not a valid name for a project. Please use a valid identifier name (alphanumeric and space).

Maybe this SO can help:
https://stackoverflow.com/questions/6692540/how-can-i-create-an-alphanumeric-regex-for-all-languages

**Comment by ajcrites** [comment]
Duplicate of #57
