### ISSUE TITLE
It's rename only android project name.

### ISSUE THREAD

**Issue by nilesh0074444** [junedomingo/react-native-rename#27]
Please help me out.
*****
./android/app/src/main/res/values/strings.xml MODIFIED
./index.android.js MODIFIED
./package.json MODIFIED
./app.json MODIFIED
./index.ios.js MODIFIED
./android/app/src/main/java/com/example BUNDLE INDENTIFIER CHANGED
./android/app/src/main/java/com/example BUNDLE INDENTIFIER CHANGED
./android/settings.gradle MODIFIED
./android/app/BUCK MODIFIED
./android/app/src/main/java/com/example/MainActivity.java MODIFIED
./android/app/src/main/java/com/example/MainApplication.java MODIFIED
./android/app/src/main/java/com/example/MainActivity.java MODIFIED
./android/app/build.gradle MODIFIED
./android/app/src/main/java/com/example/MainApplication.java MODIFIED
./android/app/src/main/AndroidManifest.xml MODIFIED
./app.json MODIFIED

**Comment by EthanChouTW** [comment]
@nilesh0074444 I met the same problem when renaming project twice. after going back to the original one and rename then it's work

**Comment by tkiefhaber** [comment]
i found this to be the case as well in version 2.1.5 of this package and react native version 0.49.3

**Comment by tkiefhaber** [comment]
I had revised the `app_name` value in the android strings.xml, which seems to be the starting point for the rename process.  After I changed it back to the original, everything worked as expected.

**Comment by nicolashemonic** [comment]
> I had revised the `app_name` value in the android strings.xml, which seems to be the starting point for the rename process. After I changed it back to the original, everything worked as expected.

I renamed partially my app (including app_name) to display to the user the new app name without changing file names. After that, react-native-rename rename only some files because it doesn't find files with their original name.

I suggest to add this precision to the readme.
