### ISSUE TITLE
React Native 0.73 MainApplication.kt and MainActivity.kt do not accept the rename

### ISSUE THREAD

**Issue by hristo87** [junedomingo/react-native-rename#289]
**Describe the bug**
After the recent update of React Native to version 0.73 and above, the MainApplication and MainActivity files, which were originally in Java, have been converted to Kotlin. Previously, the renaming of the project name inside these Java files worked as expected, but it seems to be encountering issues after the switch to Kotlin. Are there any plans to address this in future updates, or should we continue with manual updates?

**To Reproduce**
1. Create an ordinary React Native CLI 0.73.* project and use react-native-rename

**Expected behavior**
Raname project name inside MainApplication and MainActivity files

**Environment (please complete the following information):**
 - operating system: MacOs 
 - npm version: 10.2.4
 - node version: 18.18.2
 - react-native-rename version: latest ( 3.2.13)
 - react-native version: 0.73.1

**Additional context**
![SCR-20231219-lllk](https://github.com/junedomingo/react-native-rename/assets/102364045/ff0017a7-98c8-4dde-8806-4b0c2c7b994e)

**Comment by younes-ammari** [comment]
![image](https://github.com/junedomingo/react-native-rename/assets/72352932/23dd5a6b-ea6d-44b7-966b-fee9e4c41423)


I had a similar issue 

**Environment :**
"react-native-rename": "^3.2.13",
"react": "18.2.0",
"react-native": "0.73.0",
node version: 18.18.0
