### ISSUE TITLE
Error in renaming folder

### ISSUE THREAD

**Issue by markgoodyear** [junedomingo/react-native-rename#33]
I get this error when trying to run `react-native-rename`: https://d.pr/i/GhC7qW/5YzaNTTp

When it completes, the files it does overwrite, the contents end up being like this (more than just this file): https://d.pr/i/Hsb4Hg/46gtj37O

I'm on React Native 0.43.1 and `react-native-rename` 2.1.7. As some background, the project had started on RN 0.20-something so has been through a lot of changes as RN evolved.

Any ideas?

**Comment by junedomingo** [comment]
Hi @markgoodyear , unfortunately, i don't know how to solve this. 
I started this project back in RN 0.35 i think, and i didn't test it in lower version, so it only supports RN 0.35+.

**Comment by markgoodyear** [comment]
@junedomingo No problem, it's likely that things from older versions will be affecting it. I've managed to do it manually by doing a find and replace in files, and also on folder and file names. This did the trick.
