### ISSUE TITLE
Use git mv instead of just mv

### ISSUE THREAD

**Issue by brunolemos** [junedomingo/react-native-rename#34]
The git diff  is bigger than it should be because it shouldn't have `deleted`, just `renamed`.

<img width="178" alt="screenshot" src="https://user-images.githubusercontent.com/619186/32985572-8272e678-cca5-11e7-818e-ea2525ab6fe1.png">

**Comment by junedomingo** [comment]
Thanks for suggesting @brunolemos !

**Comment by brunolemos** [comment]
That way fast :) thanks!
