### ISSUE TITLE
Previous Directory Not Deleted

### ISSUE THREAD

**Issue by Geminika** [junedomingo/react-native-rename#35]
Somehow previous directory in ..\android\app\src\main\java\com is not updated to the new project name.
So, I have to rename the directory to the new project name.
Also, I have to update package keyword in MainActivity.java and MainApplicatioin.java to the new project name.
After that "react-native run-android" command will get success.

**Comment by junedomingo** [comment]
Hi @Geminika , already fixed in `v2.2.0` :-)
