### ISSUE TITLE
Seems to prefix the mv operation?

### ISSUE THREAD

**Issue by spacesuitdiver** [junedomingo/react-native-rename#37]
I dunno why in my project this seems to not rename the ios/* directories properly and errs out with many lines of:
```
fatal: source directory is empty, source=tv/ios/MyProjectName, destination=tv/ios/NewProjectName
Ignore above error if this file doesn't exist
```

**Comment by ajcrites** [comment]
This project uses `git mv` rather than just `mv`. This may not work if your project is not a git project. I think in most cases people will be using git.
