### ISSUE TITLE
git mv breaks functionality (for ejected projects)

### ISSUE THREAD

**Issue by sinewave440hz** [junedomingo/react-native-rename#38]
Hi, the changes to use git mv instead mv, while having good motivation, cause the rename operation to fail when not using version control, of course. This means that generated folders (of the type that many react native users will be using after running react-native eject, for example - we do this in our project at every major RN upgrade) cannot be renamed. Perhaps a flag to use mv instead of git mv would be the best solution?

**Comment by junedomingo** [comment]
Good point there! :-) thanks @sinewave440z

**Comment by junedomingo** [comment]
Done fixing it, so my solution is to just use "mv" if there's an error (128) in "git mv".
