### ISSUE TITLE
didn't rename anything in ios dir

### ISSUE THREAD

**Issue by pstanton** [junedomingo/react-native-rename#39]
after rename: react-native-rename NewName -b com.new.name

[Project]/ios/[OldName]
[Project]/ios/[OldName]-tvOS
[Project]/ios/[OldName]-tvOSTests
[Project]/ios/[OldName].xcodeproj
[Project]/ios/[OldName]Tests

^ still exist

**Comment by pstanton** [comment]
oh, and the java files disappeared, no MainActivity and MainApplication. had to create and change manually

**Comment by junedomingo** [comment]
@pstanton , thanks for reporting.
may i know some other details like RN version, this package version and you create your app using `react-nativ init`?

**Comment by pstanton** [comment]
react-native-cli: 2.0.1
react-native: 0.50.3
created using react-native init

**Comment by pstanton** [comment]
i'm not building for ios yet, but what do i need to do to prepare this directory? is it a straight rename of the folders or should i wait until i'm using xcode etc?

**Comment by ajcrites** [comment]
This may be due to #57 in part and #59. Please open another issue with information if you can still reproduce this with 2.3.0.
