### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by CoderHar** [junedomingo/react-native-rename#44]
see after installation i could not change name,it shows the error react-native-rename command not found

**Comment by junedomingo** [comment]
make sure to install the package correctly.
try `sudo npm install react-native-rename -g` or 
`sudo yarn global add react-native-rename`

**Comment by rodrigofbm** [comment]
Same here...

**Comment by glushkina1** [comment]
same problem. doest anyone know how to fix it?
