### ISSUE TITLE
Error: Directory should be created using "react-native init"

### ISSUE THREAD

**Issue by saifkhan192** [junedomingo/react-native-rename#46]
While running the following command in project root:
`react-native-rename "AwesomeProject"`
 I got:

> Directory should be created using "react-native init"

**Comment by junedomingo** [comment]
Hey @saifkhan192 , did you create your app using `react-native init` command?

**Comment by saifkhan192** [comment]
No. I used `create-react-native-app`.

**Comment by malibagci** [comment]
I think you should eject your Expo project

**Comment by irjencup** [comment]
I use `react-native` init and still got this problem

**Comment by ettingshausen** [comment]
`app.json` is needed. if you deleted this file.

**Comment by vijaychouhan-rails** [comment]
> `app.json` is needed. if you deleted this file.

Working fine, Thanks

**Comment by FoundersApproach** [comment]
In my case app.json was already there and still it shows same error!

To resolve this issue node version should be greater then 18. I used node version 20 with the help of node version manager (https://medium.com/devops-techable/how-to-install-nvm-node-version-manager-on-macos-with-homebrew-1bc10626181)

Thank you.

**Comment by FoundersApproach** [comment]
In my case app.json file is already there but still it gives me an error.

I solve it by make sure that file is exists in below paths:
- android/app/src/main/res/values/strings.xml
- ios/{project_name}/Info.plist

**Comment by TingaZack** [comment]
I had a similar issue with expo not so long ago, it basically means you need to build ios and android files. Just run 

> npx expo prebuild

Then, you can run react-native-rename......
