### ISSUE TITLE
Rename with <Space> EX:    APP<SPACE>NAME

### ISSUE THREAD

**Issue by rendy14s** [junedomingo/react-native-rename#49]
Hello,
I'm get the issue, if i run `react-native-rename "Nelayan Aruna"`
and re-build, thats not work. the apps display with name "NelayanAruna"

how can i put the <space> beetwen my apps ? thanks

**Comment by FRizzonelli** [comment]
Same problem here, how to add whitespace between words?

**Comment by rendy14s** [comment]
+1

**Comment by danmin25** [comment]
It may result from [https://github.com/junedomingo/react-native-rename/blob/master/src/index.js#L78](https://github.com/junedomingo/react-native-rename/blob/master/src/index.js#L78)
if you want use whitespace between two words，you can change `const nS_NewName = newName.replace(/\s/g, '');` to `const nS_NewName = newName.trim();`

**Comment by danmin25** [comment]
@rendy14s @FRizzonelli 

It may result from [https://github.com/junedomingo/react-native-rename/blob/master/src/index.js#L78](https://github.com/junedomingo/react-native-rename/blob/master/src/index.js#L78)
if you want use whitespace between two words，you can change 
```
const nS_NewName = newName.replace(/\s/g, '');
```
 to 
```
const nS_NewName = newName.trim();
```

**Comment by ajcrites** [comment]
This is a little bit complicated since the removal of spaces is used in part to build the package name for Android. I plan to refactor this so that the package name is treated separately from the bundle identifier that's provided and allow users to specify both. This will be v3.

**Comment by SimonHudec** [comment]
Type it in console without space and edit \android\app\src\main\res\values\strings.xml

**Comment by junedomingo** [comment]
Closing, check v3 now.
