### ISSUE TITLE
Custom Bundle Identifier delete main java files

### ISSUE THREAD

**Issue by vuphuctho** [junedomingo/react-native-rename#54]
**Version used:**
```
    "react": "16.0.0",
    "react-native": "0.51.0"
    "react-native-version": "2.2.2",
```

**What happened:**
- In folder `android/app/src/main/java/my/custom/bundleIdentifier` there were 2 files `MainActivity.java` and `MainApplication.java`
- Run `react-native-version newName -b my.custom.bundleIdentifier`

**Observation:**
After react-native-rename finished, the two above file are deleted. So when I create an apk from the app and install to device, app always crashes when I try to open. No error message, no bug report (I use Bugsnag to track bugs and crash exceptions)

**Comment by baselbj** [comment]
same issue

**Comment by SirPhemmiey** [comment]
This is a real bug....There's no fix until now

**Comment by geminiyellow** [comment]
yes, same error.

**Comment by vgb0332** [comment]
it just two files. just copy the older ones and paste with the newer package name corrected on both file. Easy and works fine.

**Comment by ajcrites** [comment]
Duplicate of #55
