### ISSUE TITLE
Java Packages are deleted

### ISSUE THREAD

**Issue by SirPhemmiey** [junedomingo/react-native-rename#55]
After successfully renaming my app and decided to build it, the app crashed unexpectedly on my emulator without any error output. So i dug through and discovered that both `MainActivity.java` and `MainApplication.java` have been deleted. Please is there any fix for this??? There haven't been any fix or whatsoever so far.

**Comment by st-sloth** [comment]
This issue only happens if the command is run as `react-native-rename <newName> -b <bundleIdentifier>` when `newName` is different from the current name and `bundleIdentifier` is the same as the current bundle identifier.

**Comment by Mr-Ingram** [comment]
What worked for me is that you should copy your `old Package name's`  `MainActivity.java` and `MainApplication.java` and paste them into your `new Package name's` Java folder.  You also might need to rename the text inside the Java file itself. Directions: `C:\ReactProjects\NewPackage\android\app\src\main\java\com\NewPackage`

Um, for those who can't find their java files, you can use mine as a template. Just rename `myapp` to your new name:

**MainActivity.java**
`package com.myapp;

import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "myapp";
    }
}
`

**MainApplication.java**

`package com.myapp;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new VectorIconsPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
`

Here you might not remember all of the modules you installed. If that's the case, then look in your `build.gradle` and import the correct modules. Also, if you don't know the name of the import then you can just Google it. Hope this works!

**Comment by ajcrites** [comment]
I'll look into this issue. The simple workaround for now would seem to be not to specify the bundle identifier via `-b` if it hasn't changed.

**Comment by ajcrites** [comment]
Fixed by #62
