### ISSUE TITLE
Other Languages dosen't work 

### ISSUE THREAD

**Issue by mustafaskir** [junedomingo/react-native-rename#57]
hey @junedomingo 
thanks for your great work, 
unfortunately when i tried to change App Name to Arabic Chars
i got
`is not a valid name for a project. Please use a valid identifier name (alphanumeric and space)`
thanks in advance

**Comment by cyb3rsalih** [comment]
Also doesn'tn work with Turkish alphabet characters which `ğ ü ş ı ö ç`

**Comment by ajcrites** [comment]
This will be fixed in the next release.
