### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jsappme** [junedomingo/react-native-rename#6]
```
react-native-rename NewName
The app_name value in ./android/app/src/main/res/values/strings.xml must be the same with ./ios/AppFolderName before renaming the app.
ex. ./ios/CoolApp  --->  <string name="app_name">CoolApp</string>
```
 
I am getting this error but this name is the same before I run the command.

**Comment by jsappme** [comment]
I am using rn 0.40

**Comment by dileepibtspl** [comment]
react-native-rename "Master"
/home/user-pc/.nvm/versions/node/v5.0.0/lib/node_modules/react-native-rename/lib/index.js:169
	} else if (err.code === 'ENOENT') {
	              ^

TypeError: Cannot read property 'code' of undefined
    at /home/user-pc/.nvm/versions/node/v5.0.0/lib/node_modules/react-native-rename/lib/index.js:169:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

**Comment by danilvalov** [comment]
I confirm. I have this problem too.

**Comment by csumrell** [comment]
Same problem here

**Comment by jasan-s** [comment]
I just tested it using react-native 0.43.3 and it works.

**Comment by Strayer** [comment]
Worked for me with react-native 0.44.0
