### ISSUE TITLE
MainActivity.java & MainApplication.java files are not updating with renamed package names after comman: react-native-rename "Travel App" -b com.junedomingo.travelapp

### ISSUE THREAD

**Issue by prashen** [junedomingo/react-native-rename#66]
When I am putting `react-native-rename "Travel App" -b com.junedomingo.travelapp` I can see
`android/app/src/main/java/com/projectname` The last folder wrap with a new folder name travelapp and `react-native run-android` build failed.
I have search other issue which is closed https://github.com/junedomingo/react-native-rename/pull/62

It's similar to my but I am saying it's wrapping the folder
suppose I have a project with name **"myproject"** via `react-native init myproject`
so bundle id will be like `com.myproject` and the folder names will be **myproject**.

it's wrapping the folder with **saikat**
![screen shot 2018-12-15 at 4 04 16 pm](https://user-images.githubusercontent.com/5449548/50041981-2ef47800-0083-11e9-86ea-6dc9d3ed9fcd.png)

you can see I have renamed the project from sudip to saikat with this code:
react-native-rename "saikat" -b com.saikat

**Comment by SimonHudec** [comment]
Still having this issue

**Comment by flashman2** [comment]
What is the solution? Seems the package is not usable with this bug.

**Comment by vomchik** [comment]
Fixed in the last release v2.7.0
