### ISSUE TITLE
Alphanumeric and space identifiers

### ISSUE THREAD

**Issue by matteodanelli** [junedomingo/react-native-rename#67]
_"H'ell" is not a valid name for a project. Please use a valid identifier name (alphanumeric and space)._

I noticed that the library uses a regexp to check if pattern alphanumeric is valid.
Why that?

Any restrictions? Is possible to remove it?

**Comment by matteodanelli** [comment]
I tried. And it seems to not return any error if bundle parameter is not assigned.

**Comment by ajcrites** [comment]
Bundle identifiers have to be alphanumeric (mostly). Can you give more details about the specific issue you are experiencing or what your needs are?

**Comment by matteodanelli** [comment]
"Mostly" is the problem. A lot of apps published on Google Play contains others characters in their name.
Dot, comma and apostrophes are the most used.

**Comment by ajcrites** [comment]
Dots should be allowed, but application ID's are alphanumeric: https://developer.android.com/studio/build/application-id

**Comment by matteodanelli** [comment]
Yes but I want to change the App name, which can contain comma for example.
i know that app_id cannot, but this package accepts two parameters, the first one for the app name, the second one for the app_id. 
I want to pass something with comma for app name.

**Comment by junedomingo** [comment]
Closing, check v3 now.
