### ISSUE TITLE
App has stopped after rename

### ISSUE THREAD

**Issue by arirah** [junedomingo/react-native-rename#69]
I just copied fresh new project from my existing project to another new folder . then rename this project but it has stopped after building successfully .

Is there any solution?

**Comment by SahilRS200** [comment]
i am having the same problem

**Comment by arirah** [comment]
I have fixed my problem by using react native rename 

Link :https://github.com/junedomingo/react-native-rename

**Comment by ajcrites** [comment]
Closing. Please open another issue with more details including the errors that you get.
