### ISSUE TITLE
MainActivity.java and MainApplication.java errors

### ISSUE THREAD

**Issue by dhee9000** [junedomingo/react-native-rename#72]
This issue is related to #66 

I am creating a separate issue because I noticed some additional issues:

When I ran the command 

`react-native-rename "TravelApp" -b com.travelcompany.app`

The following issues occurred:

1. Deleted my `MainApplication.java` file instead of just changing the package name.
2. In `MainActivity.java`, it didn't change the return value of `getMainComponentName()` causing app to crash on launch on android because `AppRegistry.registerComponent()` takes the name from `app.json` which IS updated but this value is not.

**Comment by priyangamani** [comment]
1.Try to copy the previous Mainapplication.java file and MainActivity.Java file
2.And Try to rename the package name inside Mainapplication.java file from (old package name)  to   com.demo (new package name)
and  similar to MainActivity.Java 
3.getMainComponentName() change the return value to "Demo" (your App Name)
![image](https://user-images.githubusercontent.com/6038069/53782024-6a963400-3f46-11e9-89d4-914af77c4654.png)

**Comment by dhee9000** [comment]
I was able to resolve the issue in my case at the time of the original post itself by following similar steps. I added this here so the actual issue with the package can be resolved. I'll try finding the issue and making a pull request.

**Comment by anastely** [comment]
@dhee9000 i have the same issue, any solutions?

**Comment by dhee9000** [comment]
@anastely I had the project under version control so I was able to find the previous files and put them where they should go. Or if the project is still fresh, you can just use a newly generated one from another project and update the package name. Or even if it isn't, do the same and then run `react-native link' and also add any manual changes that need to make to the file for any packages. If you have the error after getting it to work, just update the getMainComponentName() functions return value in MainActivory.java.

**Comment by ihsanktmr** [comment]
I had similar issue

**Comment by bilalyaqoob** [comment]
yes i got that issue and what i did is just copy those 2 files and make folder of my app name and paste those 2 files mainApplication.java and main acitivity.java and replace the old name with the new name

**Comment by louiCoder** [comment]
While renaming the app, I realized the import has `app` appended to the package name. this might need to be checked as it causes the app to crash since the name does not match.

<img width="975" alt="Screenshot 2020-08-02 at 12 13 17" src="https://user-images.githubusercontent.com/32771081/89119786-8f833380-d4b9-11ea-8298-2e3b403a58e1.png">

**Comment by vomchik** [comment]
Fixed in the last release v2.7.0

**Comment by josegoval** [comment]
This thing still happening today.
