### ISSUE TITLE
Can't change only one platform's name

### ISSUE THREAD

**Issue by cyb3rsalih** [junedomingo/react-native-rename#73]
My current project will run only in iOS so I have delete the ./android project file after `react-native init` so when I try to use react native rename, it says `project should created with react-native init` 

**Expected behaviour** 

Just change the iOS files name.

**Comment by cassianomon** [comment]
You could keep the android folder, it will not interrupt your build in iOS, alot of packages will say you need the android folder. Just ignore the android folder and you will be happier.

**Comment by cyb3rsalih** [comment]
Thank you. Actually I solve the problem,
-> `react-native init samenameApp` in another directory
-> Move the android folder to app. 
-> Now renaming works perfect. 
-> After that you can remove android again 😃
