### ISSUE TITLE
Mark repo unmaintained or call for maintainers

### ISSUE THREAD

**Issue by nicolasdet** [junedomingo/react-native-rename#76]
since there is a bug that make this repo unusable for more than 6 months.
their is many issues open for this bug #75 #72 #66 #55... 
This bug make Android app unusable after the use of this package repos which requires manual action to fix it. 
The package must be marked as not maintained and deprecated OR call for maintainers. 
It is okay to have bug in open source packages. But they should be fixed or be referenced in the readme. 
When people are looking for a package it is not to make their app unusable.

**Comment by darshkpatel** [comment]
@ajcrites It would save a lot of developers their time if this repo is marked unmaintained / allow someone else to maintain this repo

**Comment by vomchik** [comment]
@darshkpatel Hi! If you have some suggestions on how to improve or fix this library feel free a create a PRs.
Unfortunately, not all contributors have free time for working on the lib.
