### ISSUE TITLE
When use with -b parameter change your package name for android

### ISSUE THREAD

**Issue by fatihmert** [junedomingo/react-native-rename#77]
Hello,

When I am using first time with -b parameter for android change that package name. I noticed;
Android manifest file ok. But, you know package name with java nested folders name, It deletes the MainApplication and MainActivity files (or/and SplashActivity) in the original project. This works seamlessly when I reload the files.

Hope you will correct the error soon.
Best regards..

**Comment by ThunderDev1** [comment]
Getting the same behavior here, MainApplication and MainActivity files are deleted

**Comment by ridvanaltun** [comment]
i never used -b parameter but i get the same problem

**Comment by GeekRishabh** [comment]
It is also not updating the ios `BundleIdentifier` just appending up App name to default `BundleIdentifier`

**Comment by vomchik** [comment]
Fixed in the last release v2.7.0
