### ISSUE TITLE
Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by dileepibtspl** [JuneDomingo/react-native-rename#8]
react-native-rename "Master"
/home/user-pc/.nvm/versions/node/v5.0.0/lib/node_modules/react-native-rename/lib/index.js:169
} else if (err.code === 'ENOENT') {
^

TypeError: Cannot read property 'code' of undefined
at /home/user-pc/.nvm/versions/node/v5.0.0/lib/node_modules/react-native-rename/lib/index.js:169:16
at tryToString (fs.js:414:3)
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

i am getting this error help me

**Comment by JuneDomingo** [comment]
Hi @dileepibtspl, use node v6 for now. I will fix this to work with <= v5
