### ISSUE TITLE
all java file deleted

### ISSUE THREAD

**Issue by guhyeon** [junedomingo/react-native-rename#83]
after rename
all java files are removed and 
doesn't recovery
in android/app/src/main/java/com/projectName

react info 

> System:
>     OS: Windows 10
>     CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
>     Memory: 1.99 GB / 7.95 GB
>   Binaries:
>     Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 6.11.3 - C:\Users\guhyeon\AppData\Roaming\npm\npm.CMD
>   SDKs:
>     Android SDK:
>       API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
>       Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2
>       System Images: android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
>   npmPackages:
>     react: 16.8.1 => 16.9.0
>     react-native: 0.61.2 => 0.61.2

**Comment by Nicat26** [comment]
same bug in my project

**Comment by emilioheinz** [comment]
Without -b tag there is a bug, try run the command with `-b`, it should solve your problem for now.

**Comment by DeveloperDanX** [comment]
> after rename
> all java files are removed and
> doesn't recovery
> in android/app/src/main/java/com/projectName
> 
> react info
> 
> > System:
> > OS: Windows 10
> > CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
> > Memory: 1.99 GB / 7.95 GB
> > Binaries:
> > Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
> > Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
> > npm: 6.11.3 - C:\Users\guhyeon\AppData\Roaming\npm\npm.CMD
> > SDKs:
> > Android SDK:
> > API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
> > Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2
> > System Images: android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
> > npmPackages:
> > react: 16.8.1 => 16.9.0
> > react-native: 0.61.2 => 0.61.2

In my case IOS and Android builds are gone! This is a serious problem!

**Comment by sabirab2** [comment]
> 
> 
> Without -b tag there is a bug, try run the command with `-b`, it should solve your problem for now.

Even using -b option my MainActivity.java, MainApplication.java and SplashActivity.java was removed

**Comment by victorwpbastos** [comment]
Same problem here, even with -b parameter.

**Comment by celucode** [comment]
I have the same problem

**Comment by wilsolutions** [comment]
Yeah, also the repo is very outdated, last release was more than 1 year ago...
I wondering if the maintainer is willing to hand it over to somebody else to maintain it...

**Comment by rodrigodiasnoronha** [comment]
Same bug here

**Comment by drosi94** [comment]
same

**Comment by asce4s** [comment]
same

**Comment by darron1217** [comment]
Any update on this issue?

**Comment by vomchik** [comment]
Please use a latest version. 
Also provide a command which you run.

**Comment by darron1217** [comment]
@vomchik 
Oh I was using 2.4.1.
It works well on 2.6.0 latest.
Thank you 👍

**Comment by vomchik** [comment]
Fixed in v2.6.0
