### ISSUE TITLE
When using -b, "google-services.json" is ignored

### ISSUE THREAD

**Issue by elektronik2k5** [junedomingo/react-native-rename#84]
Hello and thanks for creating this package! :bowing_man: 

Although `android/app/google-services.json` isn't strictly RN, but a vendor integration, please consider processing it too - because the vast majority of RN projects will have it.

Happy to make a PR for it :)

**Comment by vomchik** [comment]
Not sure that a good idea to modify a `google-services.json`, as firstly you need to add a new bundle id in the Firebase Console.
